// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"database/sql"
)

type PriceHistory struct {
	ID        int32          `json:"id"`
	ProductID sql.NullInt32  `json:"product_id"`
	Price     sql.NullString `json:"price"`
	CheckedAt sql.NullTime   `json:"checked_at"`
}

type Product struct {
	ID           int32          `json:"id"`
	UserID       sql.NullInt32  `json:"user_id"`
	Url          sql.NullString `json:"url"`
	CurrentPrice sql.NullString `json:"current_price"`
	WebsiteID    sql.NullInt32  `json:"website_id"`
	LastChecked  sql.NullTime   `json:"last_checked"`
	AddedAt      sql.NullTime   `json:"added_at"`
}

type User struct {
	ID        int32          `json:"id"`
	Username  sql.NullString `json:"username"`
	Email     sql.NullString `json:"email"`
	Password  sql.NullString `json:"password"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type Website struct {
	ID      int32          `json:"id"`
	Name    sql.NullString `json:"name"`
	BaseUrl sql.NullString `json:"base_url"`
}
